name: betterprofile-dev

services:
  postgres:
    image: postgres
    command: "-d 1"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: betterprofile
      POSTGRES_PASSWORD: betterprofile
      POSTGRES_DB: betterprofile
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

  neon-proxy:
    image: ghcr.io/timowilhelm/local-neon-http-proxy:main
    environment:
      - PG_CONNECTION_STRING=postgres://betterprofile:betterprofile@postgres:5432/betterprofile
    ports:
      - "4444:4444"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data: {}